iso:
  mti: ASCII
  mapa-bits: ASCII
  header: ASCII
  header-tx: 12 
  header-rx: 12
  footer: ASCII
  footer-tx: 1
  footer-rx: 1
  bits-sensiveis: [2, 14, 35, 45, 52, 63]
  bits:
    '002':
      tipo-tamanho: LLVAR
      tipo-contagem: BYTE
      tamanho: 19
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '003':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 6
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '004':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '005':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '006':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '007':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '008':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 8
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '009':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 8
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '010':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 8
      tipo-dados: NUMERICO
      formato-dados: ASCII 
    '011':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 6
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '012':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 6
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '013':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 4
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '014':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 4
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '015':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 4
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '016':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 4
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '017':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 4
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '018':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 4
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '019':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '020':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '021':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '022':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '023':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '024':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '025':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '026':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '027':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 1
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '028':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 9
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '029':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 9
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '030':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 9
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '031':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 9
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '032':
      tipo-tamanho: LLVAR
      tipo-contagem: BYTE
      tamanho: 11
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '033':
      tipo-tamanho: LLVAR
      tipo-contagem: BYTE
      tamanho: 11
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '034':
      tipo-tamanho: LLVAR
      tipo-contagem: BYTE
      tamanho: 28
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '035':
      tipo-tamanho: LLVAR
      tipo-contagem: BYTE
      tamanho: 37
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '036':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 104
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '037':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '038':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 6
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '039':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '040':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '041':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '042': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 15
      tipo-dados: ALFANUMESPECIAL 
      formato-dados: ASCII
    '043':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 40
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '044':
      tipo-tamanho: LLVAR
      tipo-contagem: BYTE
      tamanho: 25
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '045':
      tipo-tamanho: LLVAR
      tipo-contagem: BYTE
      tamanho: 76
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '046':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '047':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '048':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 27
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '049':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '050':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '051':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '052':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '053':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '054': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 42
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '055': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '056': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '057': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '058': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 8
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '059': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '060':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '061':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 19
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '062':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '063':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 597
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '064': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '065': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 1
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '066': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 1
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '067': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '068': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '069': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '070':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '071': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 4
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '072': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 4
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '073': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 6
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '074':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '075':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '076':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '077':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '078':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '079': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '080':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '081':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '082': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '083': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '084': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '085': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '086':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '087':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '088':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '089':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '090':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 42
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '091': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 1
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '092': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '093': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 5
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '094': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 7
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '095':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 42
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '096': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 64
      tipo-dados: ALFANUMERICO
      formato-dados: BINARIO
    '097': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 17
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '098': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 25
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '099':
      tipo-tamanho: LLVAR
      tipo-contagem: BYTE
      tamanho: 11
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '100': 
      tipo-tamanho: LLVAR
      tipo-contagem: BYTE
      tamanho: 11
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '101': 
      tipo-tamanho: LLVAR
      tipo-contagem: BYTE
      tamanho: 17
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '102':
      tipo-tamanho: LLVAR
      tipo-contagem: BYTE
      tamanho: 28
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '103':
      tipo-tamanho: LLVAR
      tipo-contagem: BYTE
      tamanho: 28
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '104': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 100
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '105': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '106': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '107': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '108': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '109': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '110': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '111': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '112': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: BINARIO
    '113': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: BINARIO
    '114': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '115':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '116': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '117': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '118': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '119':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '120':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 29
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '121':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '122':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '123':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 553
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '124':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 9
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '125':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '126': 
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 38
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '127':
      tipo-tamanho: LLLVAR
      tipo-contagem: BYTE
      tamanho: 9
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '128':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
