iso:
  mti: BCD
  mapa-bits: BINARIO
  header: ASCII
  header-tx: 0 
  header-rx: 0
  footer: ASCII
  footer-tx: 0
  footer-rx: 0
  bits-sensiveis: [2, 14, 35, 45, 52, 55, 63]
  bits:
    '002':
      tipo-tamanho: LLBCD
      tipo-contagem: NIBBLES
      tamanho: 99
      tipo-dados: NUMERICO
      formato-dados: BCD
    '003':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: ALFANUMERICO
      formato-dados: BCD
    '004':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 6
      tipo-dados: NUMERICO
      formato-dados: BCD
    '005': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '006': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '007':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 5
      tipo-dados: NUMERICO
      formato-dados: BCD
    '008': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 8
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '009': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 8
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '010': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 8
      tipo-dados: NUMERICO
      formato-dados: ASCII 
    '011':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: BCD
    '012':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: BCD
    '013':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: NUMERICO
      formato-dados: BCD
    '014':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: NUMERICO
      formato-dados: BCD
    '015': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 4
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '016': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 4
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '017': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 4
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '018':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: NUMERICO
      formato-dados: BCD
    '019': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '020': # Nao ha na especificacao Posnet, utilizado da ISO
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '021': # Nao ha na especificacao Posnet, utilizado da ISO
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '022':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: NUMERICO
      formato-dados: BCD
    '023':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: NUMERICO
      formato-dados: BCD
    '024': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: NUMERICO
      formato-dados: BCD
    '025':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 1
      tipo-dados: NUMERICO
      formato-dados: BCD
    '026': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '027': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 1
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '028':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 9
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '029': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 9
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '030': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 9
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '031':
      tipo-tamanho: LLBCD
      tipo-contagem: BYTE
      tamanho: 99
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '032':
      tipo-tamanho: LLBCD
      tipo-contagem: BYTE
      tamanho: 99
      tipo-dados: NUMERICO
      formato-dados: BCD
    '033': 
      tipo-tamanho: LLBCD
      tipo-contagem: BYTE
      tamanho: 11
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '034': 
      tipo-tamanho: LLBCD
      tipo-contagem: BYTE
      tamanho: 28
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '035':
      tipo-tamanho: LLBCD
      tipo-contagem: NIBBLE
      tamanho: 99
      tipo-dados: ALFANUMESPECIAL
      formato-dados: BCD
    '036': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 104
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '037':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '038':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 6
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '039':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '040': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '041':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 8
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '042': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 15
      tipo-dados: ALFANUMESPECIAL 
      formato-dados: ASCII
    '043':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 107
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '044':
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '045':
      tipo-tamanho: LLBCD
      tipo-contagem: BYTE
      tamanho: 99
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '046': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '047': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '048':
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '049':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: NUMERICO
      formato-dados: BCD
    '050': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '051': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '052':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 8
      tipo-dados: ALFANUMERICO
      formato-dados: BINARIO
    '053': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '054': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '055': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: BINARIO
    '056': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '057': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '058': # Nao ha na especificacao Posnet, utilizado da ISO 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 8
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '059': 
      tipo-tamanho: LLBCD
      tipo-contagem: BYTE
      tamanho: 99
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '060':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 1
      tipo-dados: NUMERICO
      formato-dados: BCD
    '061': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '062':
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '063':
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMERICO
      formato-dados: BINARIO
    '064':  
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 64
      tipo-dados: ALFANUMERICO
      formato-dados: BINARIO
    '065':  
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 1
      tipo-dados: ALFANUMESPECIAL
      formato-dados: BINARIO
    '066': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 1
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '067': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '068': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '069':  
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 3
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '070':
      tipo-tamanho: LLBCD
      tipo-contagem: BYTE
      tamanho: 99
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '071': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 4
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '072':  
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 4
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '073': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 6
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '074': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '075': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '076': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '077': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '078': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '079': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '080': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '081': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 10
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '082': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '083': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '084': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '085': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 12
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '086': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '087': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '088': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '089': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 16
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '090': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 42
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '091': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 1
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '092': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 2
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '093':
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 5
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '094': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 7
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '095': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 42
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '096':
      tipo-tamanho: LLBCD
      tipo-contagem: BYTE
      tamanho: 99
      tipo-dados: ALFANUMERICO
      formato-dados: BINARIO
    '097': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 17
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '098': 
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 25
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '099': 
      tipo-tamanho: LLBCD
      tipo-contagem: BYTE
      tamanho: 11
      tipo-dados: NUMERICO
      formato-dados: ASCII
    '100':
      tipo-tamanho: LLBCD
      tipo-contagem: BYTE
      tamanho: 99
      tipo-dados: NUMERICO
      formato-dados: BCD
    '101':  
      tipo-tamanho: LLBCD
      tipo-contagem: BYTE
      tamanho: 17
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '102': 
      tipo-tamanho: LLBCD
      tipo-contagem: BYTE
      tamanho: 28
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '103': 
      tipo-tamanho: LLBCD
      tipo-contagem: BYTE
      tamanho: 28
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '104': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 100
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '105': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '106': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '107':  
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '108': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '109': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '110': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '111': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '112': # Nao ha na especificacao Posnet, utilizado da ISO 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: BINARIO
    '113': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: BINARIO
    '114': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '115': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '116': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '117': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '118': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '119': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '120': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '121': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '122': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '123': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '124': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 9
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '125': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '126': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMESPECIAL
      formato-dados: ASCII
    '127': 
      tipo-tamanho: LLLBCD
      tipo-contagem: BYTE
      tamanho: 999
      tipo-dados: ALFANUMERICO
      formato-dados: ASCII
    '128':  
      tipo-tamanho: FIXO
      tipo-contagem: BYTE
      tamanho: 64
      tipo-dados: ALFANUMERICO
      formato-dados: BINARIO
